INSERT INTO course_master_list(Code, Name, Credits) VALUES ('COMP 232','Mathematics for Computer Science',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('COMP 248','Object-Oriented Programming I',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ENGR 201','Professional Practice & Responsibility',1.5);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ENGR 213','Applied Ordinary Differential Equations',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('General Education Elective',null,null);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('COMP 249','Object-Oriented Programming II',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ENGR 233','Applied Advanced Calculus',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 228','System Hardware',4);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 287','Introduction to Web Applications',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('Basic Science',null,null);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('COMP 348','Principles of Programming Languages',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('COMP 352','Data Structures and Algorithms',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ENCS 282','Technical Writing and Communication',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ENGR 202','Sustainable Development and Environmental Stewardship',1.5);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('Basic Science',null,null);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('COMP 346','Operating Systems',4);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ELEC 275','Principles of Electrical Engineering',3.5);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ENGR 371','Probability and Statistics in Engineering',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 331','Introduction to Formal Methods for Software Engineering',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 341','Software Process',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('COMP 335','Introduction to Theoretical Computer Science',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 342','Software Requirements and Specifications',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 343','Software Architecture and Design I',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 384','Management Measurement and Quality Control',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ENGR 391','Numerical Methods in Engineering',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 344','Software Architecture and Design II',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 345','Software Testing, Verification and Quality Assurance',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 357','User Interface Design',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 390','Software Engineering Team Design Project',3.5);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('Elective',null,null);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 490','Capstone Software Engineering Design Project',4);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ENGR 301','Engineering Management Principles and Economics',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 321','Information Systems Security',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('Technical Elective	 ',null,null);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('Technical Elective',null,null);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 385','Control System',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('ENGR 392','Impact of Technology on Society',3);
INSERT INTO course_master_list(Code, Name, Credits) VALUES ('SOEN 490','Capstone Software Engineering Design Project',4);
